"""add_metadata_to_knowledge_node

Revision ID: 20250907_add_metadata
Revises: d6e5914ca712
Create Date: 2025-09-07

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '20250907_add_metadata'
down_revision = '20250903_fix_embeddings'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('knowledge_node', sa.Column('source_data', postgresql.JSON(astext_type=sa.Text()), nullable=True))
    op.add_column('knowledge_node', sa.Column('extractor_metadata', postgresql.JSON(astext_type=sa.Text()), nullable=True))
    op.add_column('knowledge_node', sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('knowledge_node', 'updated_at')
    op.drop_column('knowledge_node', 'extractor_metadata')
    op.drop_column('knowledge_node', 'source_data')
    # ### end Alembic commands ###