"""Add node_id to session_message table

Revision ID: 20251002_add_node_id
Revises: 20251002_remove_embeddings
Create Date: 2025-10-02 15:30:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '20251002_add_node_id'
down_revision = '20251002_remove_embeddings'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('session_message', sa.Column('node_id', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('session_message', 'node_id')
    # ### end Alembic commands ###