"""add visited_nodes to session

Revision ID: 20250907_add_visited_nodes
Revises: 20250907_add_metadata
Create Date: 2025-09-09 12:00:00.000000

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '20250907_add_visited_nodes'
down_revision = '20250907_add_metadata'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('session', sa.Column('visited_nodes', sa.Text(), nullable=True))

    # Set default value for existing records
    op.execute("UPDATE session SET visited_nodes = '[]' WHERE visited_nodes IS NULL")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('session', 'visited_nodes')
    # ### end Alembic commands ###
