"""Add node_output table

Revision ID: 20251002_add_node_output
Revises: 20251002_add_node_id
Create Date: 2025-10-02 16:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '20251002_add_node_output'
down_revision = '20251002_add_node_id'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('node_output',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('agent_id', sa.Integer(), nullable=False),
        sa.Column('node_id', sa.String(), nullable=False),
        sa.Column('node_type', sa.String(), nullable=False),
        sa.Column('output_text', sa.Text(), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
        sa.ForeignKeyConstraint(['agent_id'], ['agent.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_node_output_id'), 'node_output', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_node_output_id'), table_name='node_output')
    op.drop_table('node_output')
    # ### end Alembic commands ###