"""add last_user_input to session

Revision ID: 20250930_add_last_user_input
Revises: 20250907_add_visited_nodes
Create Date: 2025-09-30 12:00:00.000000

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '20250930_add_last_user_input'
down_revision = '0c95fe7bc071'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('session', sa.Column('last_user_input', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('session', 'last_user_input')
    # ### end Alembic commands ###