"""add conversation_id to session

Revision ID: d00d5d661a4f
Revises: 7d62be9f73fb
Create Date: 2025-08-23 03:04:41.862883

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd00d5d661a4f'
down_revision: Union[str, Sequence[str], None] = '7d62be9f73fb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('session', sa.Column('conversation_id', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('session', 'conversation_id')
    # ### end Alembic commands ###
