"""init migration

Revision ID: d6e5914ca712
Revises: 
Create Date: 2025-08-23 02:41:30.184061

"""
from typing import Sequence, Union



# revision identifiers, used by Alembic.
revision: str = 'd6e5914ca712'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
